FROM node:10-alpine

WORKDIR /src
COPY . /src

RUN set -x \
  && apk --no-cache add openssl wget \
  && yarn \
  && yarn tsc

FROM node:10-alpine

WORKDIR /app

COPY --from=0 /src/dist /app
COPY --from=0 /src/package.json /app
COPY --from=0 /src/package-lock.json /app

RUN set -x \
  && yarn install --prod \
  && yarn cache clean

CMD node /app/bin/index.js
